#!/usr/bin/env node
// Adds the `types` conditions that `tsdown`'s generated `exports` map leaves out.
//
// The bundler writes the runtime conditions, because it is the thing that knows which
// files it produced. It does not write the type conditions, and a resolver that
// looks for `types` before falling back to a sibling declaration file is entitled to
// find nothing there. Writing them here rather than by hand in `package.json` is the
// point: the map is regenerated by every build, so a hand-edited one is correct until
// the next `pnpm build` silently drops it again.

import { readFileSync, writeFileSync } from "node:fs";

const manifestPath = new URL("../package.json", import.meta.url);
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const root = manifest.exports?.["."];

if (root === undefined || typeof root !== "object") {
  throw new Error('finalize-exports: the exports map has no "." entry to complete');
}

const declaration = {
  import: "./dist/index.d.mts",
  require: "./dist/index.d.cts",
};

manifest.exports["."] = {
  types: declaration,
  ...root,
};
// The top-level `types` field is what a resolver reads when it does not understand
// `exports` at all -- `moduleResolution: classic` and some older tooling. It pointed
// at the CJS declaration, which is wrong for every ESM consumer.
manifest.types = declaration.import;

writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
console.log("finalize-exports: added the types conditions");
