#!/usr/bin/env node
// Adds the `types` conditions that `tsdown`'s generated `exports` map leaves out, plus
// the `bun` and `deno` named-runtime conditions, for every bundled subpath rather than
// the root alone. The map is regenerated by every build, so a hand-edited one is correct
// until the next `pnpm build` silently drops it again.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const requested = process.argv[2];
const manifestPath =
  requested === undefined
    ? new URL("../package.json", import.meta.url)
    : pathToFileURL(resolve(requested));
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
const exports = manifest.exports;

if (exports === undefined || typeof exports !== "object") {
  throw new Error("finalize-exports: the manifest has no exports map to complete");
}

/// Each bundled runtime path has a declaration beside it, named by the same stem and a
/// format-specific suffix. Derived rather than listed so a new subpath is covered by
/// the build that produced it.
const RUNTIME = [
  { condition: "import", extension: /\.mjs$/, declaration: ".d.mts" },
  { condition: "require", extension: /\.cjs$/, declaration: ".d.cts" },
];

/// Bun and Deno check their own key before `import` and before `require`, so this is
/// where a runtime-specific bundle would go. The value is per-format: a bare path would
/// send `require("ventiws")` under Bun to the ESM bundle and lose the CJS shape.
const NAMED_RUNTIMES = ["bun", "deno"];

function typesFor(entry) {
  const types = {};
  for (const runtime of RUNTIME) {
    const path = entry[runtime.condition];
    if (typeof path === "string")
      types[runtime.condition] = path.replace(runtime.extension, runtime.declaration);
  }
  return types;
}

function namedRuntimesFor(entry) {
  const conditions = {};
  if (typeof entry.import !== "string") return conditions;
  const formats =
    typeof entry.require === "string"
      ? { import: entry.import, require: entry.require }
      : { import: entry.import };
  for (const runtime of NAMED_RUNTIMES) conditions[runtime] = formats;
  return conditions;
}

/// Rebuilt because a second run would otherwise spread its own stale named-runtime
/// values over the fresh ones. `types` leads the object: a resolver walks the conditions
/// in order, and TypeScript only reads the `types` condition when it comes first.
function completedEntry(entry) {
  const rest = { ...entry };
  delete rest.types;
  delete rest.bun;
  delete rest.deno;
  return { types: typesFor(entry), ...namedRuntimesFor(entry), ...rest };
}

let finalized = 0;
for (const [subpath, entry] of Object.entries(exports)) {
  if (entry === null || typeof entry !== "object" || Array.isArray(entry)) continue;
  const completed = completedEntry(entry);
  if (Object.keys(completed.types).length === 0) continue;
  exports[subpath] = completed;
  finalized += 1;
}

const root = exports["."]?.types?.import;
if (typeof root !== "string") {
  throw new Error('finalize-exports: the exports map has no completed "." entry');
}
// The top-level `types` field is what a resolver reads when it does not understand
// `exports` at all -- `moduleResolution: classic` and some older tooling. It pointed
// at the CJS declaration, which is wrong for every ESM consumer.
manifest.types = root;

writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
console.log(`finalize-exports: added the types conditions for ${finalized} subpaths`);
